ignore:
  - "**/di/*Module.kt" # Remove all Koin's modules

  # GATEWAY
  - "**/api/**" # Remove all API communication related files
  - "**/AuthenticationInterceptor.kt"
  - "**/AuthenticationGateway.kt"
  - "**/AuthenticationService.kt"
  - "**/RestaurantsRepository.kt"
  - "**/RestaurantsService.kt"
  - "**/UserLocationProvider.kt"

  # PRESENTATION
  - "**/RestaurantsSplashScreen.kt"
  - "**/RestaurantsOnListScreen.kt"
  - "**/RestaurantsAdapter.kt"
  - "**/RestaurantViewHolder.kt"